#Application Properties para el ERP
spring.profiles.active=dev-h2
spring.main.banner-mode=off
spring.application.name=erp
logging.level.org.springframework=INFO
spring.jpa.open-in-view=false

# verifactu
verifactu.keystore.path=/certs/mi_certificado.p12
verifactu.keystore.password=changeit
verifactu.key.alias=mialias
verifactu.key.password=changeit
