# Perfil de desarrollo usando H2 en memoria
spring.datasource.url=jdbc:h2:mem:erpdb;DB_CLOSE_DELAY=-1
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.hikari.maximum-pool-size=5

# evitar que flyway intente migrar una base MySQL
spring.flyway.enabled=false

verifactu.cert.path=C:/Programación/segundoJAVA/shop-dao-maven/ERP/src/main/resources/certs/mi_certificado.p12
verifactu.cert.password=tu_contraseña_del_certificado
verifactu.aeat.endpoint=https://api.aeat.es/verifactu
